In [ ]:
import numpy as np

# Numpy
Numerisk python
- Array (fålt)
- Lik (listor)
- Matematiska funktioner på arrays
- Modellera vektorer och matriser

In [1]:
import numpy as np 

array1 = np.array([1,2,3,4,5,6,7,8,9])
print(array1[0])
print(array1[-1])
print(array1[1:4]) # sliceing

lista = [1,2,3,4]

print(lista*2)
print(array1*2) # varje element multipliceras med 2

1
9
[2 3 4]
[1, 2, 3, 4, 1, 2, 3, 4]
[ 2  4  6  8 10 12 14 16 18]


In [7]:
import numpy as np 

x = np.arange(1,10)
print(x)

# y = kx + m
def f(k,x,m):
    y = k*x + m
    return y
# y = 2x + 2
print(f(2,x,2))
# y = x + 1
print(f"y = {f(1,x,1)}") 

plt.plot(x,f(1,x,1))

[1 2 3 4 5 6 7 8 9]
[ 4  6  8 10 12 14 16 18 20]
y = [ 2  3  4  5  6  7  8  9 10]


NameError: name 'plt' is not defined